import {
  Activity,
  BadgeCheck,
  BellRing,
  BookMarked,
  BookOpen,
  Building,
  CalendarClock,
  CalendarDays,
  ChartColumn,
  ChartLine,
  CircleCheck,
  CirclePlus,
  ClipboardCheck,
  ClipboardList,
  Clock,
  FileDiff,
  FilePenLine,
  FileText,
  Flag,
  FolderOpen,
  Gavel,
  GraduationCap,
  HandCoins,
  Handshake,
  HeartHandshake,
  HeartPulse,
  History,
  IdCard,
  KeyRound,
  Inbox,
  Landmark,
  LayoutDashboard,
  Library,
  ListChecks,
  ListTodo,
  MapPin,
  MessageSquareText,
  MessageSquareWarning,
  Network,
  Newspaper,
  NotebookPen,
  PenLine,
  Percent,
  PiggyBank,
  Plug,
  Radar,
  Receipt,
  RefreshCw,
  Scale,
  ScanSearch,
  ScrollText,
  SearchCheck,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Siren,
  SquareKanban,
  Stamp,
  Stethoscope,
  Target,
  TrendingUp,
  Umbrella,
  UserRound,
  UserRoundCheck,
  UserSearch,
  Users,
  UsersRound,
  Wallet,
  Workflow,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';
import type { LucideIconName } from './module-registry.js';

/** Registry icon names to Lucide components. Typed so a missing icon fails to compile. */
export const ICONS: Readonly<Record<LucideIconName, LucideIcon>> = {
  'layout-dashboard': LayoutDashboard,
  'shield-check': ShieldCheck,
  'badge-check': BadgeCheck,
  'id-card': IdCard,
  'scan-search': ScanSearch,
  landmark: Landmark,
  'map-pin': MapPin,
  // The module map names `file-signature`; Lucide 1.x renamed that icon to `file-pen-line`.
  'file-signature': FilePenLine,
  wallet: Wallet,
  umbrella: Umbrella,
  activity: Activity,
  'heart-handshake': HeartHandshake,
  'graduation-cap': GraduationCap,
  'list-checks': ListChecks,
  'user-round-check': UserRoundCheck,
  settings: Settings,
  'list-todo': ListTodo,
  newspaper: Newspaper,
  'calendar-days': CalendarDays,
  'clipboard-check': ClipboardCheck,
  'folder-open': FolderOpen,
  flag: Flag,
  'clipboard-list': ClipboardList,
  'bell-ring': BellRing,
  users: Users,
  stethoscope: Stethoscope,
  'calendar-clock': CalendarClock,
  gavel: Gavel,
  'square-kanban': SquareKanban,
  'hand-coins': HandCoins,
  'refresh-cw': RefreshCw,
  'file-text': FileText,
  'user-search': UserSearch,
  history: History,
  'users-round': UsersRound,
  'notebook-pen': NotebookPen,
  stamp: Stamp,
  scale: Scale,
  'book-open': BookOpen,
  'heart-pulse': HeartPulse,
  network: Network,
  'file-diff': FileDiff,
  clock: Clock,
  handshake: Handshake,
  percent: Percent,
  receipt: Receipt,
  'piggy-bank': PiggyBank,
  'chart-column': ChartColumn,
  'search-check': SearchCheck,
  'shield-alert': ShieldAlert,
  siren: Siren,
  radar: Radar,
  'chart-line': ChartLine,
  target: Target,
  'message-square-text': MessageSquareText,
  'message-square-warning': MessageSquareWarning,
  'trending-up': TrendingUp,
  library: Library,
  'circle-check': CircleCheck,
  inbox: Inbox,
  workflow: Workflow,
  'user-round': UserRound,
  'pen-line': PenLine,
  building: Building,
  plug: Plug,
  'book-marked': BookMarked,
  'scroll-text': ScrollText,
  'key-round': KeyRound,
  'circle-plus': CirclePlus,
};

/** Design system §6: 1.75px stroke; 20px in navigation, 16px inline. Decorative by default. */
export function Icon({
  name,
  size = 20,
  ...rest
}: { name: LucideIconName; size?: number } & Omit<LucideProps, 'ref' | 'size'>) {
  const Component = ICONS[name];
  return (
    <Component aria-hidden="true" focusable="false" size={size} strokeWidth={1.75} {...rest} />
  );
}
